In [2]:
import pandas as pd
import requests
import time
import wget
# inline

In [ ]:
# https://www.kaggle.com/datasets/dubradave/nfl-draft-history-1990-present (dubradave kaggle dataset)
url = "https://raw.githubusercontent.com/dhoff316/datascience-club-F26/refs/heads/main/NFLDraftHistory.csv"
wget.download(url)

In [ ]:
# gather hist player data
years = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
schools = ["Alabama", "Arkansas", "Auburn", "Florida", "Georgia", "Kentucky", "LSU", "Mississippi State", "Missouri", "Oklahoma", "Ole Miss", "South Carolina", "Tennessee", "Texas", "Texas A&M", "Vanderbilt"]
all_data = []

for year in years:
    for school in schools:
        time.sleep(0.5)
        r = requests.get("https://api.collegefootballdata.com/stats/player/season",
                    headers={"Authorization": "Bearer olVvNEK2/yEC2USr1s+zQWta7nLmzM4P1IwXJot9wxU8FIIKob1UPcWq45OEQkXw"},
                    params={
                            "year": year, # loop 2014 - 2025
                            "conference": "SEC",
                            "team": school, # loop schools
                            "seasonType": "both"
                    }
                    )
        data = r.json()
        all_data.extend(data)

df = pd.DataFrame(all_data)
df.to_csv("sec_player_data_2014_2025.csv", index=False)

In [ ]:
rosters = []

for year in years:
    for school in schools:
        time.sleep(0.5)
        r = requests.get("https://api.collegefootballdata.com/roster",
                    headers={"Authorization": "Bearer olVvNEK2/yEC2USr1s+zQWta7nLmzM4P1IwXJot9wxU8FIIKob1UPcWq45OEQkXw"},
                    params={
                            "team": school,
                            "year": year,
                            "classification": "fbs"
                    }
                    )
        data = r.json()
        rosters.extend(data)

df1 = pd.DataFrame(rosters)
df1.to_csv("sec_roster_data_2014_2025.csv", index=False)

In [ ]:
#all_ids = df["playerId"].unique() # 4691

#for ids in all_ids: prob not worth it

In [28]:
# wrangle
df = pd.read_csv("sec_player_data_2014_2025.csv")
df1 = pd.read_csv("sec_roster_data_2014_2025.csv")
df3 =  pd.read_csv("NFLDraftHistory.csv")

In [29]:
df = df.pivot_table(values="stat", index=["playerId", "player", "season", "category", "team", "position"], columns="statType").reset_index().rename_axis(columns=None)
df # fillna

,playerId,player,season,category,team,position,ATT,AVG,CAR,COMPLETIONS,...,TD,TFL,TOT,XPA,XPM,YDS,YPA,YPC,YPP,YPR
0,102597,Will Rogers,2022,fumbles,Mississippi State,QB,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102597,Will Rogers,2022,passing,Mississippi State,QB,610.0,NaN,NaN,414.0,...,35.0,NaN,NaN,NaN,NaN,3963.0,6.5,NaN,NaN,NaN
2,102597,Will Rogers,2022,receiving,Mississippi State,QB,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,13.0
3,102597,Will Rogers,2022,rushing,Mississippi State,QB,NaN,NaN,44.0,NaN,...,0.0,NaN,NaN,NaN,NaN,-165.0,NaN,-3.8,NaN,NaN
4,102597,Will Rogers,2023,fumbles,Mississippi State,QB,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17148,5295969,Brady Hart,2025,rushing,Texas A&M,QB,NaN,NaN,1.0,NaN,...,0.0,NaN,NaN,NaN,NaN,9.0,NaN,9.0,NaN,NaN
17149,5296720,Tiger Riden Jr.,2025,rushing,Texas A&M,RB,NaN,NaN,11.0,NaN,...,1.0,NaN,NaN,NaN,NaN,45.0,NaN,4.1,NaN,NaN
17150,5297763,Tyler Williams,2025,receiving,Georgia,WR,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,7.0
17151,5305951,Oliver Robbins,2025,kicking,Missouri,PK,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
17152,5306254,Diesel Moye,2025,defensive,Mississippi State,DL,NaN,NaN,NaN,NaN,...,0.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df1

,id,firstName,lastName,team,weight,height,jersey,year,position,homeCity,homeState,homeCountry,homeLatitude,homeLongitude,homeCountyFIPS,recruitIds
0,-1000925,Kieran,Williams,Alabama,243.0,76.0,49.0,2014,TE,Lawrenceville,GA,USA,33.956215,-83.987962,13135.0,[]
1,-1000924,Paul,Waldrop,Alabama,285.0,76.0,69.0,2014,OL,Phenix City,AL,USA,32.470976,-85.000765,1113.0,[]
2,-1000923,MK,Taylor,Alabama,230.0,70.0,59.0,2014,LS,Oxford,AL,USA,33.585369,-85.914282,1121.0,[]
3,-1000922,Nate,Staskelunas,Alabama,206.0,75.0,22.0,2014,DB,Grenville,NC,USA,45.466902,-97.393700,46037.0,[]
4,-1000921,Geno,Smith,Alabama,NaN,NaN,24.0,2014,DB,Atlanta,GA,USA,33.749099,-84.390185,13121.0,['149095']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23127,5294065,Ryder,Brownstein,Vanderbilt,175.0,74.0,35.0,1,WR,Los Angeles,CA,USA,34.053691,-118.242767,6037.0,[]
23128,5294066,Jack,Wanzung,Vanderbilt,184.0,72.0,37.0,2,CB,Chicago,IL,USA,41.875562,-87.624421,17031.0,['221890']
23129,5294067,Wils,Jackson,Vanderbilt,205.0,77.0,88.0,2,WR,Franklin,TN,USA,35.925193,-86.868937,47187.0,[]
23130,5294068,Justin,Dewers,Vanderbilt,195.0,74.0,47.0,2,PK,Plano,TX,USA,33.013676,-96.692510,48085.0,[]
23131,5294069,Nikhil,Jefferson,Vanderbilt,330.0,73.0,93.0,2,DL,Tampa,FL,USA,27.947760,-82.458444,12057.0,[]

In [15]:
df1[df1["id"].duplicated()] # request overlap

,id,firstName,lastName,team,weight,height,jersey,year,position,homeCity,homeState,homeCountry,homeLatitude,homeLongitude,homeCountyFIPS,recruitIds
1933,-1000895,Bradley,Sylve,Alabama,180.0,72.0,3.0,2015,DB,Port Sulphur,LA,USA,29.480495,-89.693953,22075.0,['152226']
1934,-1000893,A'Shawn,Robinson,Alabama,312.0,76.0,86.0,2015,DL,Fort Worth,TX,USA,32.753177,-97.332746,48439.0,['145633']
1935,-1000892,Jarran,Reed,Alabama,313.0,76.0,90.0,2015,DL,Goldsboro,NC,USA,35.384884,-77.992765,37191.0,['186333']
1937,-1000890,Chris,Posa,Alabama,281.0,76.0,65.0,2015,OL,Commerce,MI,USA,42.591143,-83.490772,26125.0,[]
1938,-1000889,D.J.,Pettway,Alabama,270.0,74.0,57.0,2015,DL,Pensacola,FL,USA,30.421309,-87.216915,12033.0,['152327']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23114,5218656,Jake,Balis,Vanderbilt,200.0,69.0,42.0,3,RB,Granger,IN,USA,41.753382,-86.110838,18141.0,[]
23115,5218658,Larry,Benton III,Vanderbilt,221.0,76.0,48.0,2,TE,Houston,TX,USA,29.758938,-95.367697,48201.0,[]
23116,5218659,Max,Fisher,Vanderbilt,270.0,74.0,57.0,4,OL,Nashville,TN,USA,36.162230,-86.774353,47037.0,[]
23117,5218660,CJ,Williams,Vanderbilt,331.0,78.0,62.0,3,OL,Amityville,NY,USA,40.680247,-73.420523,36103.0,['109936']
23118,5218663,Boski,Barrett,Vanderbilt,178.0,71.0,13.0,3,WR,Knoxville,TN,USA,35.960395,-83.921026,47093.0,['109378']

In [25]:
df1.drop_duplicates(subset="id", keep="last", inplace=True)
df[df["playerId"].isin(df1["id"])]

,playerId,player,season,category,team,position,ATT,AVG,CAR,COMPLETIONS,...,TD,TFL,TOT,XPA,XPM,YDS,YPA,YPC,YPP,YPR
0,102597,Will Rogers,2022,fumbles,Mississippi State,QB,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102597,Will Rogers,2022,passing,Mississippi State,QB,610.0,NaN,NaN,414.0,...,35.0,NaN,NaN,NaN,NaN,3963.0,6.5,NaN,NaN,NaN
2,102597,Will Rogers,2022,receiving,Mississippi State,QB,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,13.0
3,102597,Will Rogers,2022,rushing,Mississippi State,QB,NaN,NaN,44.0,NaN,...,0.0,NaN,NaN,NaN,NaN,-165.0,NaN,-3.8,NaN,NaN
4,102597,Will Rogers,2023,fumbles,Mississippi State,QB,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17148,5295969,Brady Hart,2025,rushing,Texas A&M,QB,NaN,NaN,1.0,NaN,...,0.0,NaN,NaN,NaN,NaN,9.0,NaN,9.0,NaN,NaN
17149,5296720,Tiger Riden Jr.,2025,rushing,Texas A&M,RB,NaN,NaN,11.0,NaN,...,1.0,NaN,NaN,NaN,NaN,45.0,NaN,4.1,NaN,NaN
17150,5297763,Tyler Williams,2025,receiving,Georgia,WR,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,7.0
17151,5305951,Oliver Robbins,2025,kicking,Missouri,PK,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
17152,5306254,Diesel Moye,2025,defensive,Mississippi State,DL,NaN,NaN,NaN,NaN,...,0.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df = df.merge(df1, how="inner", left_on="playerId", right_on="id") # merge
df[df["playerId"] == 504300]

,playerId,player,season,category,team_x,position_x,ATT,AVG,CAR,COMPLETIONS,...,jersey,year,position_y,homeCity,homeState,homeCountry,homeLatitude,homeLongitude,homeCountyFIPS,recruitIds
147,504300,Jacob Carter,2014,puntReturns,Tennessee,WR,NaN,6.9,NaN,NaN,...,27.0,2014,WR,Nashville,TN,USA,36.16223,-86.774353,47037.0,[]
148,504300,Jacob Carter,2014,receiving,Tennessee,WR,NaN,NaN,NaN,NaN,...,27.0,2014,WR,Nashville,TN,USA,36.16223,-86.774353,47037.0,[]

In [33]:
# drop, fill?, sort, rename, confirm
df.columns

Index(['playerId', 'player', 'season', 'category', 'team_x', 'position_x',
       'ATT', 'AVG', 'CAR', 'COMPLETIONS', 'FGA', 'FGM', 'FUM', 'INT', 'In 20',
       'LONG', 'LOST', 'NO', 'PCT', 'PD', 'PTS', 'QB HUR', 'REC', 'SACKS',
       'SOLO', 'TB', 'TD', 'TFL', 'TOT', 'XPA', 'XPM', 'YDS', 'YPA', 'YPC',
       'YPP', 'YPR', 'id', 'firstName', 'lastName', 'team_y', 'weight',
       'height', 'jersey', 'year', 'position_y', 'homeCity', 'homeState',
       'homeCountry', 'homeLatitude', 'homeLongitude', 'homeCountyFIPS',
       'recruitIds'],
      dtype='str')

In [ ]:
#df3 match on name

In [ ]:
# EDA